# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Electronics
# Product.create(category: "electronics", title: "Samsung 55-inch Screen", description: "Samsung UN55RU7100FXZA Flat 55-Inch 4K UHD 7 Series Ultra HD Smart TV (2019 Model)", price: 600, image_url: "https://images-na.ssl-images-amazon.com/images/I/91GMSrYPaHL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/Samsung-UN55RU7100FXZA-55-Inch-Ultra-Smart/dp/B07NC9J2M5/ref=zg_mw_172659_15?_encoding=UTF8&psc=1&refRID=F2T4ES091KFZGRY7EVR6")
# Product.create(category: "electronics", title: "Nebula Portable Home Theater", description: "Nebula, by Anker, Mars II 300 ANSI lm Portable Home Theater Projector with 720p 30-150'' DLP Picture, 10W Speakers, Android 7.1, 1-Second Autofocus, 4-Hour Playtime, Broad Connectivity, and Miracast", price: 550, image_url: "https://images-na.ssl-images-amazon.com/images/I/81ZZG9gNwQL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/Anker-Portable-Projector-Autofocus-Connectivity/dp/B07BXDW18Z/ref=zg_mw_1266092011_6?_encoding=UTF8&psc=1&refRID=R3SJ2WT8MR1EPV7PEHQB")
# Product.create(category: "electronics", title: "TCL 55-inch Screen", description: "TCL 55R617 55-Inch 4K Ultra HD Roku Smart LED TV (2018 Model)", price: 800, image_url: "https://images-na.ssl-images-amazon.com/images/I/91y7-3BmUfL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/TCL-55R617-55-Inch-Ultra-Smart/dp/B079N9HDNQ/ref=zg_mw_1266092011_40?_encoding=UTF8&psc=1&refRID=R3SJ2WT8MR1EPV7PEHQB")
# Product.create(category: "electronics", title: "Sony 65-inch Screen", description: "Sony KD65X750F 65-Inch 4K Ultra HD Smart LED TV", price: 1000, image_url: "https://images-na.ssl-images-amazon.com/images/I/91bu9k4syFL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/Sony-KD65X750F-65-Inch-Ultra-Smart/dp/B07D1GSZYQ/ref=zg_mw_1266092011_48?_encoding=UTF8&psc=1&refRID=R3SJ2WT8MR1EPV7PEHQB")
# Product.create(category: "electronics", title: "Cinemood Portable Movie Theater", description: "CINEMOOD Portable Movie Theater- Includes Disney Family Favorites, Streams Netflix, Amazon Prime Videos and Youtube - Anytime, Anyplace", price: 400, image_url: "https://images-na.ssl-images-amazon.com/images/I/51qCqTUqqQL._SL1365_.jpg", link_to_amazon: "https://www.amazon.com/CINEMOOD-Portable-Theater-Favorites-Streams/dp/B079HJB9P8/ref=zg_mw_1266092011_7?_encoding=UTF8&psc=1&refRID=R3SJ2WT8MR1EPV7PEHQB")
# Product.create(category: "electronics", title: "BenQ Home Theater Projector", description: "BenQ HT3550 4K Home Theater Projector with HDR10 and HLG | 2000 Lumens | 95% DCI-P3 and 100% Rec.709 for Accurate Colors | Short Throw | Lens Shift | 3D", price: 2000, image_url: "https://images-na.ssl-images-amazon.com/images/I/818DPv1OVDL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/BenQ-HT3550-Theater-Projector-Accurate/dp/B07MTY97T2/ref=zg_mw_1266092011_27?_encoding=UTF8&psc=1&refRID=R3SJ2WT8MR1EPV7PEHQB")
# Product.create(category: "electronics", title: "Yamaha Home Theater Box System", description: "Yamaha YHT-4930UBL  5.1-Channel Home Theater in a Box System with Bluetooth", price: 460, image_url: "https://images-na.ssl-images-amazon.com/images/I/31yNM4CQTjL.jpg", link_to_amazon: "https://www.amazon.com/Yamaha-YHT-4930UBL-5-1-Channel-Theater-Bluetooth/dp/B071JY862G/ref=zg_mw_281056_3?_encoding=UTF8&psc=1&refRID=41JQSCC0298F6PP9TW0Y")
# Product.create(category: "electronics", title: "Pioneer Home Theater System", description: "Pioneer 5.1 Home Theater System HTP-074", price: 449, image_url: "https://images-na.ssl-images-amazon.com/images/I/71XOHlew7kL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/Pioneer-Home-Theater-System-HTP-074/dp/B01JOBIFP2/ref=zg_mw_281056_4?_encoding=UTF8&psc=1&refRID=41JQSCC0298F6PP9TW0Y")
# Product.create(category: "electronics", title: "VIZIO Premium Home Theater", description: "VIZIO SB46514-F6 46-Inch 5.1.4 Premium Home Theater Sound System with Dolby Atmos and Wireless Subwoofer Plus Rear Surround Speakers", price: 1000, image_url: "https://images-na.ssl-images-amazon.com/images/I/410cKd-q4uL._SL1000_.jpg", link_to_amazon: "https://www.amazon.com/VIZIO-SB46514-F6-Wireless-Subwoofer-Surround/dp/B07GTQWMYQ/ref=zg_mw_281056_5?_encoding=UTF8&psc=1&refRID=41JQSCC0298F6PP9TW0Y")
# Product.create(category: "electronics", title: "Sonos Surround Set Home Theater System", description: "Sonos 5.1 Surround Set - Home Theater System with Playbar, Sub and 2 Sonos Ones", price: 1796, image_url: "https://images-na.ssl-images-amazon.com/images/I/51KOT4remSL._SL1000_.jpg", link_to_amazon: "https://www.amazon.com/Sonos-5-1-Surround-Set-Theater/dp/B076DFP5HC/ref=zg_mw_281056_13?_encoding=UTF8&psc=1&refRID=41JQSCC0298F6PP9TW0Y")
# Product.create(category: "electronics", title: "iWear AV920 Virtual 62-inch Eyewear", description: "Advanced Optics: 32-degree field of view 3/4-inch eye relief and 5/16-inch eyebox. 2.5-inch intraocular distance (IOD). Color corrected 10th order aspherical lens with diffractive surface", price: 350, image_url: "https://images-na.ssl-images-amazon.com/images/I/31M8sNsKsOL.jpg", link_to_amazon: "https://www.amazon.com/VIDEO-AV920-VIRTUAL-62-EYEWEAR/dp/B000X471P0/ref=zg_mw_3213034011_43?_encoding=UTF8&psc=1&refRID=JD5NX42JPVF8VYQSP6FP")
# Product.create(category: "electronics", title: "Cinemizer OLED Multimedia Video Glasses", description: "Cinemizer 1909-127 - Lightweight comfortable design. Folding arms for easy storage. HDMI, Apple, AV-3.5mm 4 pin input capability", price: 789, image_url: "https://images-na.ssl-images-amazon.com/images/I/61tGgBvYMXL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/Cinemizer-1909-127-Multimedia-Video-Glasses/dp/B0091OI530/ref=zg_mw_3213034011_2?_encoding=UTF8&psc=1&refRID=JD5NX42JPVF8VYQSP6FP")
# Product.create(category: "electronics", title: "Moverio BT-300 - Epson Smart Glasses", description: "Ideal platform for developing AR apps — seamlessly blend digital content into the world around you with this highly transparent Si-OLED display.  Powered by an Intel Atom chipset and built on an Android platform — familiar and open development environment, plus access to the Moverio SDK with developer tools and resources", price: 779, image_url: "https://images-na.ssl-images-amazon.com/images/I/61WTiiY20AL._SL1200_.jpg", link_to_amazon: "https://www.amazon.com/Moverio-BT-300-Smart-Glasses-Developer/dp/B01N6HN2AW/ref=zg_mw_3213034011_7?_encoding=UTF8&psc=1&refRID=JD5NX42JPVF8VYQSP6FP")
# Product.create(category: "electronics", title: "FatShark Modular 3D FPV Google Headset", description: "HDO Dominator - FSV1122 - Resolution: 960 x 720 (1024 x 800 screen). Field of View: 37° Supports HDMI-in @ 1080P. Image Aspect Ratio: 4:3", price: 500, image_url: "https://images-na.ssl-images-amazon.com/images/I/71u-CJc5mKL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/FatShark-Dominator-FSV1122-Modular-Goggles/dp/B07CZZRW74/ref=zg_mw_3213034011_18?_encoding=UTF8&psc=1&refRID=JD5NX42JPVF8VYQSP6FP")
# Product.create(category: "electronics", title: "Flysight Falcon Video Googles", description: "Flysight Falcon FG02 FPV Video Goggles with DVR HDMI in, 5.8G 40CH Wireless RC Drone Goggles FPV Custom Receiver Module Compatible with DJI Fatshark Eachine Goggles", price: 300, image_url: "https://images-na.ssl-images-amazon.com/images/I/616O1KzxhsL._SL1044_.jpg", link_to_amazon: "https://www.amazon.com/Goggles-Glasses-Receive-Flysight-Version/dp/B07H4LX9TN/ref=zg_mw_3213034011_41?_encoding=UTF8&psc=1&refRID=JD5NX42JPVF8VYQSP6FP")
# Product.create(category: "electronics", title: "eufy Boostiq Robovac", description: "eufy Boostiq Robovac 11S (Slim), 1300PA Strong Suction, Super Quiet, Self-Charging Robotic Vacuum Cleaner, Cleans Hard Floors to Medium-Pile Carpets (Black)", price: 230, image_url: "https://images-na.ssl-images-amazon.com/images/I/71TmTj7HjNL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/eufy-RoboVac-Suction-Self-Charging-Medium-Pile/dp/B079QYYGF1/ref=zg_mw_electronics_10?_encoding=UTF8&psc=1&refRID=58Q6KCGFKWE48D21Z7AH")
# Product.create(category: "electronics", title: "Echo Show - Amazon", description: "Echo Show (2nd Gen) – Premium sound and a vibrant 10.1” HD screen - Charcoal", price: 230, image_url: "https://images-na.ssl-images-amazon.com/images/I/61t2lISns3L._SL1000_.jpg", link_to_amazon: "https://www.amazon.com/All-new-Echo-Show-2nd-Gen/dp/B077SXWSRP/ref=zg_mw_electronics_27?_encoding=UTF8&psc=1&refRID=58Q6KCGFKWE48D21Z7AH")
# Product.create(category: "electronics", title: "Panasonic Lumix - 4K Digital Camera", description: "PANASONIC LUMIX G85 4K Digital Camera, 12-60mm Power O.I.S. Lens, 16 Megapixel Mirrorless Camera, 5 Axis In-Body Dual Image Stabilization, 3-Inch Tilt and Touch LCD, DMC-G85MK (Black)", price: 1000, image_url: "https://images-na.ssl-images-amazon.com/images/I/811yIm41V3L._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/PANASONIC-Mirrorless-12-60mm-Megapixels-DMC-G85MK/dp/B01M050N05/ref=zg_mw_electronics_30?_encoding=UTF8&psc=1&refRID=58Q6KCGFKWE48D21Z7AH")
# Product.create(category: "electronics", title: "GoPro HERO7", description: "GoPro HERO7 Black — Waterproof Digital Action Camera with Touch Screen 4K HD Video 12MP Photos Live Streaming Stabilization", price: 400, image_url: "https://images-na.ssl-images-amazon.com/images/I/71I13Ws9GCL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/GoPro-HERO7-Black-Waterproof-Streaming-Stabilization/dp/B07GDGZCCH/ref=zg_mw_electronics_32?_encoding=UTF8&psc=1&refRID=58Q6KCGFKWE48D21Z7AH")
# Product.create(category: "electronics", title: "Dell Inspiron 5000", description: "Premium Flagship 2019 New Dell Inspiron 15 5000 15.6-inch Full HD Touchscreen Laptop Intel Quad-Core i7-8550U/i5-8250U 8GB/16GB/32GB RAM 256GB/512GB/1TB SSD 2TB HDD Backlit KB Webcam WiFi Win 10", price: 1600, image_url: "https://images-na.ssl-images-amazon.com/images/I/71MwqfG4RNL._SL1500_.jpg", link_to_amazon: "https://www.amazon.com/dp/B07FRPLYCG/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07FRPLYCG&pd_rd_w=rmjpp&pf_rd_p=8a8f3917-7900-4ce8-ad90-adf0d53c0985&pd_rd_wg=QyC8s&pf_rd_r=GJJ4ANM9GX7YJE4FJWZ4&pd_rd_r=b7f1b6b3-7b42-11e9-bee9-f381f43bc426")
